import Head from 'next/head'
import Navigation from '../components/Navigation'
import Fusszeile from '../components/Footer'

export default function Layout({children}) {
    return (
        <div>
            <Head>
                <title>Indian Sneakers</title>
                <meta name="description" content="Generated by Indian Sneakers" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <div className='center container'>
            {children}
            </div>
            <Fusszeile />
        </div>
    )
}
